import React, { useRef, useState } from 'react';

export default function WebRTCVideoCall() {
  // References to attach the video streams to the HTML video tags
  const localVideoRef = useRef(null);
  const remoteVideoRef = useRef(null);

  // Reference to hold the WebRTC connection object
  const peerConnectionRef = useRef(null);

  // 1. Configure the STUN Server (Using Google's free STUN servers)
  const rtcConfig = {
    iceServers: [
      {
        urls: [
          'stun:stun1.l.google.com:19302',
          'stun:stun2.l.google.com:19302',
        ],
      },
    ],
  };

  // Step 1: Get access to the user's Camera and Microphone
  const startLocalStream = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
      // Display the local video stream on the screen
      if (localVideoRef.current) {
        localVideoRef.current.srcObject = stream;
      }
    } catch (error) {
      console.error("Error accessing camera and microphone:", error);
    }
  };

  // Step 2: Create the WebRTC Connection and generate an Offer
  const startCall = async () => {
    // Initialize the Peer Connection with the STUN servers
    const peerConnection = new RTCPeerConnection(rtcConfig);
    peerConnectionRef.current = peerConnection;

    // Add local video/audio tracks to the connection so the other person can see/hear you
    const localStream = localVideoRef.current.srcObject;
    if (localStream) {
      localStream.getTracks().forEach((track) => {
        peerConnection.addTrack(track, localStream);
      });
    }

    // Listen for the remote video stream coming from the other person
    peerConnection.ontrack = (event) => {
      if (remoteVideoRef.current) {
        // Attach the remote stream to the remote video tag
        remoteVideoRef.current.srcObject = event.streams[0];
      }
    };

    // Listen for ICE Candidates generated by the STUN server
    peerConnection.onicecandidate = (event) => {
      if (event.candidate) {
        // TODO: Send this ICE candidate to your Signaling Server (via WebSocket)
        console.log("ICE Candidate generated. Send to signaling server:", event.candidate);
      }
    };

    // Create the SDP Offer (Device capabilities)
    const offer = await peerConnection.createOffer();

    // Set the local description (Tell your browser what your setup is)
    await peerConnection.setLocalDescription(offer);

    // TODO: Send this 'offer' to the other peer via your Signaling Server (WebSocket)
    console.log("SDP Offer created. Send to signaling server:", offer);
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h2>WebRTC Video Call (React/Next.js)</h2>

      <div style={{ display: 'flex', gap: '20px', marginBottom: '20px' }}>
        {/* Local Video Stream */}
        <div>
          <h3>You</h3>
          <video
            ref={localVideoRef}
            autoPlay
            playsInline
            muted
            style={{ width: '300px', background: '#333', borderRadius: '8px' }}
          />
        </div>

        {/* Remote Video Stream */}
        <div>
          <h3>Remote Peer</h3>
          <video
            ref={remoteVideoRef}
            autoPlay
            playsInline
            style={{ width: '300px', background: '#333', borderRadius: '8px' }}
          />
        </div>
      </div>

      <div style={{ display: 'flex', gap: '10px' }}>
        <button onClick={startLocalStream} style={btnStyle}>1. Start Camera</button>
        <button onClick={startCall} style={btnStyle}>2. Start Call (Create Offer)</button>
      </div>
    </div>
  );
}

// Simple inline styles for the buttons
const btnStyle = {
  padding: '10px 20px',
  cursor: 'pointer',
  backgroundColor: '#0070f3',
  color: 'white',
  border: 'none',
  borderRadius: '5px',
  fontWeight: 'bold'
};